server:
  address: 127.0.0.1:8631
logging:
  factory: zap # zap | logrus
  formatter: normal # normal | json
  appenders:
    # - type: file
    #   options:
    #     log-file-dir: ./logs
    #     log-file-name: application.log
    #     max-file-size: 52428800 # 字节
    #     max-file-backups: 20
    #     max-file-age: 86400s
    #     local-time: true
    #     compress: true
    - type: stdout
  root-name: learngolang
  root-level: INFO
  package-levels:
    "protocol/ip/tcp": WARN
#kube-config-file: /path/to/kube-conf.yml
#kube-config-data: '
#apiVersion: v1
#kind: Config
#preferences: {}
#current-context: monitor@kubernetes
#clusters:
#  - cluster:
#      # certificate-authority: /etc/kubernetes/pki/ca.crt
#      # cat ca.crt | base64 -w 0
#      certificate-authority-data: LS0tLS1CRUdJTiB ...
#      server: https://192.168.1.1:6443
#    name: kubernetes
#users:
#  - name: monitor
#    user:
#      # client-certificate: /tmp/monitor.crt
#      # client-key: /tmp/monitor.key
#      # cat monitor.crt | base64 -w 0
#      client-certificate-data: LS0tLS1CRUdJTiB ...
#      # cat monitor.key | base64 -w 0
#      client-key-data: LS0tLS1CRUdJTiBSU0E ...
#contexts:
#  - name: monitor@kubernetes
#    context:
#      cluster: kubernetes
#      user: monitor
#'