server:
  address: 127.0.0.1:8630
agent:
  capture:
    devices:
      - prefix: any
        duration: 2s
        snaplen: 120 # bytes
        promisc: true
    #    - prefix: ens192
    #      duration: 2s
    #      snaplen: 120 # bytes
    #      promisc: true
    par-type: routine # routine | reactor
    routine:
      parallelism: 4
      ch-buffer-size: 2048
      share-chan: true
    reactor:
      buffer: 2048
  collect:
    server-type: grpc            # grpc | http | log
    server-addr: localhost:50051 # localhost:50051 | "http://127.0.0.1:8630/collect"
    parallelism: 1
    par-buff-size: 64
collector:
  kube-cluster-id: kubernetes
  # kube-config-file: /path/to/kube-conf.yml
  kube-config-data: |-
    apiVersion: v1
    kind: Config
    preferences: {}
    current-context: monitor@kubernetes
    clusters:
      - cluster:
          # certificate-authority: /etc/kubernetes/pki/ca.crt
          # cat ca.crt | base64 -w 0
          certificate-authority-data: LS0tLS1CRUdJTiB ...
          server: https://192.168.1.1:6443
        name: kubernetes
    users:
      - name: monitor
        user:
          # client-certificate: /tmp/monitor.crt
          # client-key: /tmp/monitor.key
          # cat monitor.crt | base64 -w 0
          client-certificate-data: LS0tLS1CRUdJTiB ...
          # cat monitor.key | base64 -w 0
          client-key-data: LS0tLS1CRUdJTiBSU0E ...
    contexts:
      - name: monitor@kubernetes
        context:
          cluster: kubernetes
          user: monitor
  grpc-host: 0.0.0.0
  grpc-port: 50051
logging:
  factory: zap      # zap | logrus
  formatter: normal # normal | json
  appenders:
    - type: stdout
  #    - type: file
  #      options:
  #        log-file-dir: ./logs
  #        log-file-name: application.log
  #        max-file-size: 52428800 # 字节
  #        max-file-backups: 20
  #        max-file-age: 86400s
  #        local-time: true
  #        compress: true
  root-name: learngolang
  root-level: INFO
  package-levels:
    "protocol/ip/tcp": WARN